name: MonoGS
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.9.0
  - pip=22.3.1
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - git+https://github.com/facebookresearch/pytorch3d.git
