inherit_from: "configs/mono/bonn/base_config.yaml"

Dataset:
  dataset_path: "datasets/bonn/rgbd_bonn_dataset/rgbd_bonn_balloon_tracking/"
  Calibration:
    fx: 542.822841
    fy: 542.576870
    cx: 315.593520
    cy: 237.756098
    k1: 0.039903
    k2: -0.099343
    p1: -0.000730
    p2: -0.000144
    k3: 0.000000
    width: 640
    height: 480
    depth_scale: 5000.0
    segmented: True
    distorted: True


